### ISSUE TITLE
When scrolling with offset, page jumps to zero offset when animation is complete

### ISSUE THREAD

**Issue by joshuatuscan** [bySabi/react-scrollchor#30]
I'm using Scrollchor with no child anchor and have the offset set to -170. After the animation completes, when the hash URL updates, the page scrolls to 0 offset for the element. Seems like maybe the event doesn't have preventDefault set.

**Comment by joshuatuscan** [comment]
I believe this was the result of default hash behavior conflicting with the component animation. I used the disableHistory prop and it solved my problem of not jumping to 0 offset. If you use history and update the hashes, it still jumps however.

**Comment by gitjul** [comment]
I'm experiencing the same issue.

**Comment by bySabi** [comment]
The problem is on: [updateHistory](https://github.com/bySabi/react-scrollchor/blob/master/src/helpers.js#L45) function and the intended behavior of `window.location.hash` that can't be changed even with `event.preventDefault`, see this thread: https://stackoverflow.com/questions/3870057/how-can-i-update-window-location-hash-without-jumping-the-document

In order of prevent jump and still use history the user must handle back button by itself.

We can follow two possible paths:
* add a `prefix` parameter to `updateHistory`  or
* make updateHistory a callback, then the user can pass the implementation that he prefer.

Another idea?... What will be desirable?

**Comment by bySabi** [comment]
It solved on new release, `5.1.0`.

Please update your code and tell me is ok.

Thanks for report the issue.

**Comment by joshuatuscan** [comment]
Seems to be working great. Thanks for the update!

**Comment by gitjul** [comment]
Thank you!
