### ISSUE TITLE
location(url) getting changed

### ISSUE THREAD

**Issue by ShivanshSharma1** [bySabi/react-scrollchor#38]
Is there any way to stop it from changing location(url).

**Comment by bySabi** [comment]
I don't understand what you need. Please explain a little more

**Comment by ShivanshSharma1** [comment]
When I click on a ScrollChor element, it takes me to the element with the given id but it also adds #(id) at the end of the url. Is there any way to prevent it from adding the id at the end of the url.

**Comment by bySabi** [comment]
@ShivanshSharma1  Adding the `id` at the end of the URL is done by the browser when you click on a `<a>` element as is this case.

Try the `simulateClick` API and the childrenless `Scrollchor` as in this example: https://github.com/some-react-components/react-scrollchor/issues/17

Sorry I can't try it myself because I'm out of time.

Tell me how it went.

**Comment by bySabi** [comment]
Maybe using `disableHistory: true` is enough

**Comment by ShivanshSharma1** [comment]
It worked, Thanks. Sorry, I missed the props section in the docs

**Comment by bySabi** [comment]
I glad it worked 👍
